### ISSUE TITLE
How to compare with SeqSLAM

### ISSUE THREAD

**Issue by ghost** [ktsintotas/trackingDOseqSLAM#1]
I am able to plot the "Precision/Recall" of this system and everything seems ok, but what do I need to change on "OpenSLAM-org/openslam_openseqslam" in order to compare both systems (for KITTI sequence "00")? As I am doing, SeqSLAM seems so much worse compared with the results of the paper and with the result that I am getting from this system.

**Comment by ktsintotas** [comment]
Dear Adriel, as I can remember, I have made some modifications for seqSLAM to work as a loop-closure detection pipeline rather a place recognizer in different weather conditions. Feel free to send me an e-mail to forward my code. I hope that this could help your research.
